# artgris_file_manager:
#     conf:
#         files:
#             dir: "%kernel.project_dir%/public/uploads/imagenes"
#             type: 'file'
#         images:
#             dir: "%kernel.project_dir%/public/uploads/imagenes"
#             type: 'image'
artgris_file_manager:
    conf:
        public:
            dir: '%kernel.project_dir%/public/uploads/imagenes'
            type: 'image'
            upload:
                max_file_size: 1048576 # (1Mo) size in bytes
                max_width: 900
                max_height: 768
                override: true


fos_ck_editor:
    default_config: basic_config
    configs:
        basic_config:
            toolbar: standard
            filebrowserBrowseRoute: file_manager
            filebrowserBrowseRouteParameters:
                conf: files
                module: ckeditor
            filebrowserImageBrowseRoute: file_manager
            filebrowserImageBrowseRouteParameters:
                conf: public
                module: ckeditor