twig:
    form_themes:
        - '@KMSFroalaEditor/Form/froala_widget.html.twig'

kms_froala_editor:
    language: es
    saveURL: ""
    saveInterval: 0
    saveParam: "content"
    imageUploadFolder: "/public/upload"
    # imageUploadRemoteUrls: false
    imageUploadPath: ""
    publicDir: "/public"


