twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@KMSFroalaEditor/Form/froala_widget.html.twig'
        - 'bootstrap_4_layout.html.twig'
    globals:
        usuario: '@App\Service\SeguridadService'

when@test:
    twig:
        strict_variables: true
